# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HomeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.GenericIPAddressField()),
                ('mask', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Providerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('networks', models.ManyToManyField(blank=True, to='info.Network')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.PortsInfo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Providerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ip_add', models.GenericIPAddressField()),
                ('description', models.CharField(blank=True, max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ports', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vlaninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.PositiveIntegerField()),
                ('networks', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.Network')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Switch'),
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='vlan',
            field=models.ManyToManyField(to='info.Vlaninfo'),
        ),
        migrations.AddField(
            model_name='portsinfo',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Switch'),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.ApartmentNumber'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.District'),
        ),
        migrations.AddField(
            model_name='address',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.HomeNumber'),
        ),
        migrations.AddField(
            model_name='address',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Quarter'),
        ),
    ]
