# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_switch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlaninfo',
            name='networks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Network'),
        ),
    ]
