# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_oid_base_snmp_community'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OID_Base',
            new_name='OidBase',
        ),
        migrations.RenameModel(
            old_name='SNMP_Community',
            new_name='SnmpCommunity',
        ),
    ]
