# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20170417_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.SwitchModel'),
        ),
    ]
