# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_portsinfo_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portsinfo',
            name='selected',
        ),
        migrations.AddField(
            model_name='portsinfo',
            name='select',
            field=models.BooleanField(default=False, verbose_name='Используется'),
        ),
    ]
