# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20170417_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Address'),
        ),
    ]
