# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_subscriber_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='portsinfo',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Subscriber'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='port',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Address'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.SwitchModel'),
        ),
    ]
