# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20170419_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='port',
        ),
    ]
