# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_remove_subscriber_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portsinfo',
            name='number',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='port', to='info.Subscriber', validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)]),
        ),
    ]
