# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20170421_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portsinfo',
            name='number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='portsinfo',
            name='subscriber',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port', to='info.Subscriber'),
        ),
    ]
