# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_remove_subscriber_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portsinfo',
            name='switch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='port', to='info.Switch'),
        ),
    ]
