# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20170421_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portsinfo',
            name='subscriber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='port', to='info.Subscriber'),
        ),
        migrations.AlterField(
            model_name='portsinfo',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Switch'),
        ),
    ]
