# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20170421_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='apartmentnumber',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='homenumber',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='oidbase',
            name='value',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='providerinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='snmpcommunity',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_add',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='switchmodel',
            name='model',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('district', 'quarter', 'home', 'apartment')]),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([('name', 'address')]),
        ),
    ]
