# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20170426_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
