# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20170426_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portsinfo',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriber', to='info.PortsInfo'),
        ),
    ]
