# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20170428_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenumber',
            name='number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
