# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20170525_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['district', 'quarter', 'home', 'apartment']},
        ),
        migrations.AlterModelOptions(
            name='apartmentnumber',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='homenumber',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='portsinfo',
            options={'ordering': ['switch', 'number']},
        ),
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='homenumber',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
