# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20171006_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenumber',
            name='litera',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        )

    ]
