# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20171006_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homenumber',
            unique_together=set([('number', 'litera')]),
        ),
    ]
