# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_auto_20171006_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenumber',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
